# Use a Java 17 base image
FROM eclipse-temurin:17-jdk-alpine

# Copy the JAR file and rename
COPY target/employees-0.0.1-SNAPSHOT.jar employees.jar

# Corrected entrypoint with typo fix
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar", "employees.jar"]
